config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/games/upcoming', to: 'games#upcoming', as: :games_upcoming
  get '/games/past', to: 'games#past', as: :games_past
  get '/games/public', to: 'games#public_games', as: :games_public
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  resources :users, only: [:index, :show] do
    resources :wishlists
  end
  # Routes for HasFriendship
    post '/users/:id/friendships',    to: 'friendships#request_frd', as: :friendships_request
    post '/users/:id',   to: 'friendships#confirm_frd', as: :friendships_confirm
    post '/users/:id',   to: 'friendships#decline_frd', as: :friendships_decline
    delete '/users/:id',  to: 'friendships#remove_frd', as: :friendships_remove
  resources :list_preferences
  resources :courses do
    resources :attachments
  end
  resources :games do
    resources :attachments
    resources :guests, only: [:index, :create, :update]
    resources :likes
    resources :wishgames
  end

  resources :guests, only: [:destroy]
  get '/games/approve_user/:id', to: 'guests#approve_user', as: :approve_user
  get '/games_buddies', to: 'games#games_buddies', as: :games_buddies
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
      collection do
      delete :empty_trash
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end
    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
    @conversation.receipts_for(current_user).mark_as_read
  end

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.erb
<% if conversation.is_unread?(current_user)%>
  <div class='list-conversation-item active'>
<% else %>
  <div class='list-conversation-item'>
<% end %>

  <div class="list-conversation-left-index">
    <%= render 'conversations/participant', conversation: conversation %>
  </div>

  <div class="list-conversation-middle-index">
    <h4><%= link_to conversation.subject, conversation_path(conversation) %></h4>
    <span></span>
    <p><%= conversation.last_message.body %>

        <% if conversation.last_message.subject.match(/wants to be your buddy/) && current_user.requested_friends.include?(conversation.last_message.sender) && !current_user.friends_with?(conversation.last_message.sender) %>
                <%= link_to 'Accept request', friendships_confirm_path(conversation.last_message.sender), method: :post, class: "btn btn-outline-success btn-sm" %>
                <%= link_to 'Decline request', friendships_decline_path(conversation.last_message.sender), method: :post, class: "btn btn-outline-danger btn-sm" %>
      <% end %>
    </span></p>
  </div>

  <div class="list-conversation-right-index">
    <div class="conv-right-up">
      <small><span class="text-muted"><%= conversation.last_message.created_at.strftime("%-D, %H:%M") %></span></small>
    </div>
    <div class="conv-right-down">
      <% if conversation.is_trashed?(current_user) %>
      <%= link_to '<i class="fas fa-trash-restore-alt"></i>'.html_safe, restore_conversation_path(conversation), method: :post %>
      <% else %>
      <%= link_to '<i class="fas fa-trash"></i>'.html_safe, conversation_path(conversation), method: :delete,
                  data: {confirm: 'Are you sure?'} %>
      <% if conversation.is_unread?(current_user) %>
        <%= link_to '<i class="far fa-envelope-open"></i>'.html_safe, mark_as_read_conversation_path(conversation), method: :post %>
      <% end %>
    <% end %>
  </div>
  </div>
  </li>
</div>

app/views/conversations/_participant.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <% if !participant.photo.blank? %>
      <img src="<%= participant.photo %>" class="avatar-bordered"/>
    <% else %>
      <%= gravatar_for participant %>
    <% end %>
    <h5><%= participant.first_name %></h5>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<div class="conversation-container min-height-container" style="width: 0vw;">
  <div class="conversation-left">
    <h1 style="color:rgba(122, 107, 189, 0.7);
">Messages</h1>
<%= link_to '<i class="fas fa-plus-circle fa-2x"></i>'.html_safe, new_message_path %></span>
    <ul class="list-mailbox">
      <li class='nav-mailbox <%= 'active' if params[:box] == 'inbox' %>'>
        <%= link_to 'Inbox', conversations_path(box: :inbox)%>
      </li>
      <li class='nav-mailbox <%= 'active' if params[:box] == 'sent' %>'>
        <%= link_to 'Sent', conversations_path(box: :sent)%>
      </li>
      <li class='nav-mailbox <%= 'active' if params[:box] == 'trash' %>'>
        <%= link_to 'Trash', conversations_path(box: :trash)%>
      </li>
    </ul>
  </div>

  <div class="conversation-right">
    <% if @box == 'trash' %>
    <p><%= link_to '<i class="fas fa-recycle"></i> Empty trash'.html_safe, empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
    data: {confirm: 'Are you sure?'} %></p>
    <% end %>
    <ul class="list-mail-group">
      <%= render partial: 'conversations/conversation', collection: @conversations %>
    </ul>
   <div class="flickr_pagination">
   <%= will_paginate %>
  </div>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="container-message min-height-container">

  <div class="message-left">
    <div class="inbox-back">
    <h4><%= link_to '<i class="fas fa-inbox fa-lg"></i> Back to inbox'.html_safe, conversations_path%></h4>
    </div>


  </div>

  <div class="message-right">
    <h1>Chatting with <% @conversation.participants.each do |participant| %>
      <% unless participant == current_user %>
        <%= link_to participant.first_name, user_path(participant) %>
        <% if !participant.photo.blank? %>
            <img src="<%= participant.photo %>" class="avatar-bordered img-rounded"/>
        <% else %>
          <%= gravatar_for participant %><br>
        <% end %>
      <% end %>
    <% end %> </h1>
    <h2><%= @conversation.subject %></h2>
    <%= form_tag reply_conversation_path(@conversation), method: :post do %>
      <div class="input-message">
        <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
        <%= submit_tag "Send Message", class: 'send-button-right' %>
      </div>
    <% end %>

    <% @conversation.receipts_for(current_user).sort.reverse.each do |receipt| %>
      <div class="<%= receipt.message.sender == current_user ? 'message-byme' : 'message-byother' %> ">
        <% message = receipt.message %>
        <% if !message.sender.photo.blank? %>
          <img src="<%= message.sender.photo %>" class="avatar-bordered img-rounded"/>
        <% else %>
          <%= gravatar_for message.sender, 30 %>
        <% end %>
        <span style="font-weight: lighter; font-size: small;"><%= message.created_at.strftime("%-D, %H:%M") %></span>
          <strong><%= message.sender.first_name %></strong>
        <span style="align-self: self-end;"><%= message.body %></span>
      </div>
    <% end %>

      </div>
    </div>
  </div>
</div>