config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/games/upcoming', to: 'games#upcoming', as: :games_upcoming
  get '/games/past', to: 'games#past', as: :games_past
  get '/games/public', to: 'games#public_games', as: :games_public
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  resources :users, only: [:index, :show] do
    resources :wishlists
  end
  # Routes for HasFriendship
    post '/users/:id/friendships',    to: 'friendships#request_frd', as: :friendships_request
    post '/users/:id',   to: 'friendships#confirm_frd', as: :friendships_confirm
    post '/users/:id',   to: 'friendships#decline_frd', as: :friendships_decline
    delete '/users/:id',  to: 'friendships#remove_frd', as: :friendships_remove
  resources :list_preferences
  resources :courses do
    resources :attachments
  end
  resources :games do
    resources :attachments
    resources :guests, only: [:index, :create, :update]
    resources :likes
    resources :wishgames
  end

  resources :guests, only: [:destroy]
  get '/games/approve_user/:id', to: 'guests#approve_user', as: :approve_user
  get '/games_buddies', to: 'games#games_buddies', as: :games_buddies
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
      collection do
      delete :empty_trash
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :games, dependent: :destroy
  has_many :guests, dependent: :destroy
  has_many :user_preferences, dependent: :destroy
  has_many :list_prefs, through: :user_preferences
  has_many :likes, dependent: :destroy
  has_many :wishlists
  has_many :wishgames, through: :wishlists
  mount_uploader :photo, PhotoUploader
  # messageable = this Class can use mailboxer gem
  acts_as_messageable
  has_friendship

  # validates :gender, presence: true

  def in_game?(game)
    Guest.find_by(user: self, game: game)
  end

  def next_game



  end

  def all_games
   self.games  + self.guests.map { |g| g.game }
  end

  def upcoming_games
    games = self.all_games.select { |game|  game.time >= Date.today }

    games.sort { |game|  game.time }
  end

  def past_games
    games = self.all_games.select { |game|  game.time < Date.today }

    games.sort { |game|  game.time }
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do |resource|
      Wishlist.create!(user: resource)
      perso_id = params["user"]["list_pref_ids"]
      list = perso_id.map do |id|
        if !id.blank?
          ListPref.find(id)
        end
      end
      list.each do |l|
        if !l.nil?
          UserPreference.create!(user: resource, list_pref: l)
        end
      end
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super do |resource|
      perso_id = params["user"]["list_pref_ids"]
      list = perso_id.map do |id|
        if !id.blank?
          ListPref.find(id)
        end
      end
      list.each do |l|
        if !l.nil?
          UserPreference.create!(user: resource, list_pref: l)
        end
      end
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :first_name,
      :last_name,
      :birth_date,
      :gender,
      :handicap,
      :pro,
      :about_me,
      :photo,
      :current_city,
      :list_pref_ids,
      :language
    ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: [
      :first_name,
      :last_name,
      :birth_date,
      :gender,
      :handicap,
      :pro,
      :about_me,
      :photo,
      :current_city,
      :list_pref_ids,
      :language
    ])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index]
  before_action :authenticate_user!

  def index
    #list all users
    @users = User.order('created_at DESC').paginate(page: params[:page])
    #list buddies of the current_user
    @buddies = current_user.friends
    #list of users requested friendship to the current_user (so list of buddies to be accepted or declined)
    @requested_buddies = current_user.requested_friends
  end

  def show

  #{ where("date >= ?", [Date.today]).order('date ASC, created_at ASC') }
    @next_game = @user.upcoming_games.first

    @future_games = @user.upcoming_games.drop(1)

    @past_games = @user.past_games
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

end

app/views/users/_buddies.html.erb
  <% if @buddies.empty? %>
  <p class="buddy-body">No buddy <i class="fas fa-frown text-center text-secondary "></i></p>
  <% end %>
  <div class="buddy-container min-height-container w-90">
  <!-- <div class="row justify-content-between"> -->
    <% @buddies.each do |user| %>
      <% unless user.email == "info@golfybuddy.com" %>


        <div class="buddy-card  text-center">
          <svg width="40" class="add_btn" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
          <rect width="40" height="40" rx="20" fill="#72C472"/>
          <path d="M30 13.5772L16.2857 27L10 20.8479L11.6114 19.2707L16.2857 23.8345L28.3886 12L30 13.5772Z" fill="white"/>
          </svg>

          <%= link_to user_path(user.id) do%>
            <% if !user.photo.blank? %>
              <div>
                <img src= "<%= user.photo%>", class="buddy-photo" alt="">
              </div>
            <% else %>
              <%= image_tag gravatar_image_url(user.email), class: "buddy-photo" %>
            <% end %>

            <div class="text-center text-warning pt-2">
              <strong><%= user.first_name %> <%= user.last_name %></strong>
            </div>
          <% end %>


          <div class="text-secondary text-left pl-3 ml-5">
            <div class="pt-4">
              <svg width="22" class="mr-2" height="29" viewBox="0 0 22 29" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M21 11.0432C21 17.8182 11 27.8182 11 27.8182C11 27.8182 1 17.8182 1 11.0432C1 4.68773 6.16773 1 11 1C15.8323 1 21 4.68773 21 11.0432Z" stroke="#676767" stroke-opacity="0.8" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="square"/>
                <path d="M11.0004 14.636C13.0087 14.636 14.6367 13.008 14.6367 10.9996C14.6367 8.99134 13.0087 7.36328 11.0004 7.36328C8.99207 7.36328 7.36401 8.99134 7.36401 10.9996C7.36401 13.008 8.99207 14.636 11.0004 14.636Z" stroke="#676767" stroke-opacity="0.8" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="square"/>
              </svg>
              <% if !user.current_city || user.current_city == "" %>
                NA
              <% elsif user.current_city %>
                <%= user.current_city %>
              <% end %>
            </div>
            <div class="pt-4">
              <svg width="25" class="mr-2" height="23" viewBox="0 0 25 23" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M6.36667 13.975C3.14207 14.79 1 16.2282 1 17.8666C1 20.4073 6.14893 22.4666 12.5 22.4666C18.8511 22.4666 24 20.4073 24 17.8666C24 15.3259 18.8511 13.2666 12.5 13.2666" stroke="#676767" stroke-opacity="0.9" stroke-miterlimit="10" stroke-linecap="square"/>
              <path d="M9.43335 17.8667V1L16.3333 4.06667L9.43335 7.13333" stroke="#676767" stroke-opacity="0.9" stroke-miterlimit="10"/>
              </svg>
              <% if user.handicap %>
                Handicap: <%= user.handicap %>
              <% else %>
                Handicap : NA
              <% end %>
            </div>

            <div class="pt-4">
              <% if user.language %>
                <% if user.language == "English" %>
                  <% url = "https://www.countryflags.io/gb/flat/32.png" %>
                <% elsif user.language == "Spanish" %>
                  <% url =  "https://www.countryflags.io/es/flat/32.png" %>
                  <% elsif user.language == "French" %>
                  <% url =  "https://www.countryflags.io/fr/flat/32.png" %>
                <% else %>
                  <% url =  "https://www.countryflags.io/#{user.language[0..1].downcase}/flat/32.png" %>
                <% end %>
                <img src=<%= url %> class="mr-1">
              <% end %>
              <%= user.language %>
            </div>
          </div>
          <div class="text-center message">
            <% unless current_user == user %>
              <%= link_to '<i class="far fa-envelope fa-lg"></i>'.html_safe, new_message_path(to: user), class: "msg_btn " %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</ul>

app/views/users/_buddy_requests.html.erb
<% if current_user.requested_friends.empty? %>
    <p class="text-secondary text-center min-height-container" style="position: relative; top: 10vh">No request <i class="fas fa-frown text-center text-secondary "></i></p>
  <% end %>
  <div class="buddy-container w-90">
  <!-- <div class="row justify-content-between"> -->
    <% current_user.requested_friends.each do |user| %>



        <div class="buddy-card  text-center">

          <%= link_to 'Accept', friendships_confirm_path(user), method: :post, class: "btn btn-success btn-accept" %>

          <%= link_to user_path(user.id) do%>
            <% if !user.photo.blank? %>
              <div>
                <img src= "<%= user.photo%>", class="buddy-photo" alt="">
              </div>
            <% else %>
              <%= image_tag gravatar_image_url(user.email), class: "buddy-photo" %>
            <% end %>

            <div class="text-center text-warning pt-2">
              <strong><%= user.first_name %> <%= user.last_name %></strong>
            </div>
          <% end %>


          <div class="text-secondary text-left pl-3 ml-5">
            <div class="pt-4">
              <svg width="22" class="mr-2" height="29" viewBox="0 0 22 29" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M21 11.0432C21 17.8182 11 27.8182 11 27.8182C11 27.8182 1 17.8182 1 11.0432C1 4.68773 6.16773 1 11 1C15.8323 1 21 4.68773 21 11.0432Z" stroke="#676767" stroke-opacity="0.8" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="square"/>
                <path d="M11.0004 14.636C13.0087 14.636 14.6367 13.008 14.6367 10.9996C14.6367 8.99134 13.0087 7.36328 11.0004 7.36328C8.99207 7.36328 7.36401 8.99134 7.36401 10.9996C7.36401 13.008 8.99207 14.636 11.0004 14.636Z" stroke="#676767" stroke-opacity="0.8" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="square"/>
              </svg>
              <% if !user.current_city || user.current_city == "" %>
                NA
              <% elsif user.current_city %>
                <%= user.current_city %>
              <% end %>
            </div>
            <div class="pt-4">
              <svg width="25" class="mr-2" height="23" viewBox="0 0 25 23" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M6.36667 13.975C3.14207 14.79 1 16.2282 1 17.8666C1 20.4073 6.14893 22.4666 12.5 22.4666C18.8511 22.4666 24 20.4073 24 17.8666C24 15.3259 18.8511 13.2666 12.5 13.2666" stroke="#676767" stroke-opacity="0.9" stroke-miterlimit="10" stroke-linecap="square"/>
              <path d="M9.43335 17.8667V1L16.3333 4.06667L9.43335 7.13333" stroke="#676767" stroke-opacity="0.9" stroke-miterlimit="10"/>
              </svg>
              <% if user.handicap %>
                Handicap: <%= user.handicap %>
              <% else %>
                Handicap : NA
              <% end %>
            </div>

            <div class="pt-4">
              <% if user.language %>
                <% if user.language == "English" %>
                  <% url = "https://www.countryflags.io/gb/flat/32.png" %>
                <% elsif user.language == "Spanish" %>
                  <% url =  "https://www.countryflags.io/es/flat/32.png" %>
                  <% elsif user.language == "French" %>
                  <% url =  "https://www.countryflags.io/fr/flat/32.png" %>
                <% else %>
                  <% url =  "https://www.countryflags.io/#{user.language[0..1].downcase}/flat/32.png" %>
                <% end %>
                <img src=<%= url %> class="mr-1">
              <% end %>
              <%= user.language %>
            </div>
          </div>
          <div class="text-center message">
            <% unless current_user == user %>
              <%= link_to '<i class="far fa-envelope fa-lg"></i>'.html_safe, new_message_path(to: user), class: "msg_btn " %>
            <% end %>
          </div>
        </div>

    <% end %>
  </div>

app/views/users/_non_buddies.html.erb
  <!-- USERS BEGIN-->

<div class="buddy-container min-height-container w-90">
  <!-- <div class="row justify-content-between"> -->


  <!-- DEBUT DES BUDDY CARDS - TOUT LE MONDE -->
  <% @users.each do |user| %>
      <% if user != current_user && (user != User.find_by(email: "info@golfybuddy.com") && (!user.friends_with?(current_user) && (!current_user.requested_friends.include?(user) && !user.requested_friends.include?(current_user) )) )%>
        <div class="buddy-card  text-center">



          <%= link_to  friendships_request_path(user.id), method: :post do %>
            <svg class="add_btn" width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M30.6377 21.8722H21.2091V31.3008H18.0663V21.8722H8.6377V18.7294H18.0663V9.30078H21.2091V18.7294H30.6377V21.8722Z" fill="#686B6F"/>
              <rect width="40" height="40" rx="20" fill="#7A7A7A" fill-opacity="0.26"/>
            </svg>
          <% end %>


        <!-- PHOTO -->

        <%= link_to user_path(user.id) do%>
          <% if !user.photo.blank? %>
            <div>
              <img src= "<%= user.photo%>", class="buddy-photo" alt="">
            </div>
          <% else %>
              <%= image_tag gravatar_image_url(user.email), class: "buddy-photo" %>
          <% end %>

          <div class="text-center text-warning pt-2">
            <strong><%= user.first_name %> <%= user.last_name %></strong>
          </div>
        <% end %>

        <div class="text-secondary text-left pl-3 ml-5">
          <div class="pt-4">
            <svg width="22" class="mr-2" height="29" viewBox="0 0 22 29" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M21 11.0432C21 17.8182 11 27.8182 11 27.8182C11 27.8182 1 17.8182 1 11.0432C1 4.68773 6.16773 1 11 1C15.8323 1 21 4.68773 21 11.0432Z" stroke="#676767" stroke-opacity="0.8" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="square"/>
              <path d="M11.0004 14.636C13.0087 14.636 14.6367 13.008 14.6367 10.9996C14.6367 8.99134 13.0087 7.36328 11.0004 7.36328C8.99207 7.36328 7.36401 8.99134 7.36401 10.9996C7.36401 13.008 8.99207 14.636 11.0004 14.636Z" stroke="#676767" stroke-opacity="0.8" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="square"/>
            </svg>
            <% if !user.current_city || user.current_city == "" %>
              NA
            <% elsif user.current_city %>
              <%= user.current_city %>
            <% end %>
          </div>
          <div class="pt-4">
            <svg width="25" class="mr-2" height="23" viewBox="0 0 25 23" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M6.36667 13.975C3.14207 14.79 1 16.2282 1 17.8666C1 20.4073 6.14893 22.4666 12.5 22.4666C18.8511 22.4666 24 20.4073 24 17.8666C24 15.3259 18.8511 13.2666 12.5 13.2666" stroke="#676767" stroke-opacity="0.9" stroke-miterlimit="10" stroke-linecap="square"/>
              <path d="M9.43335 17.8667V1L16.3333 4.06667L9.43335 7.13333" stroke="#676767" stroke-opacity="0.9" stroke-miterlimit="10"/>
            </svg>
            <% if user.handicap %>
              Handicap: <%= user.handicap %>
            <% else %>
              Handicap : NA
            <% end %>
          </div>

          <div class="pt-4">
            <% if user.language %>
          <%= image_tag "speaker.png", alt: "alttext", style: "width: 25px; margin-right: 10px" %><%= user.language %>
          <% end %>
          </div>

        </div>

        <div class="text-center message">
          <% unless current_user == user %>
            <%= link_to '<i class="far fa-envelope fa-lg"></i>'.html_safe, new_message_path(to: user), class: "msg_btn " %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<nav>
  <div class="nav nav-tabs-buddies mt-5 content-justify" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active text-center text-warning tab-title" id="nav-buddy-tab" data-toggle="tab" href="#nav-buddies" role="tab" aria-controls="nav-home" aria-selected="true"><h3 class="buddy-titles">Your buddies</h3></a>
    <a class="nav-item nav-link text-center text-warning tab-title" id="nav-users-tab" data-toggle="tab" href="#nav-users" role="tab" aria-controls="nav-profile" aria-selected="false"><h3 class="buddy-titles">Find a buddy</h3></a>
    <a class="nav-item nav-link text-center text-warning tab-title" id="nav-request-tab" data-toggle="tab" href="#nav-requests" role="tab" aria-controls="nav-profile" aria-selected="false"><h3 class="buddy-titles">Buddy requests</h3></a>
  </div>
</nav>

<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-buddies" role="tabpanel" aria-labelledby="nav-profile-tab">
    <%= render "users/buddies" %>
  </div>

  <div class="tab-pane fade" id="nav-users" role="tabpanel" aria-labelledby="nav-profile-tab">
    <%= render "users/non_buddies" %>
  </div>


  <div class="tab-pane fade" id="nav-requests" role="tabpanel" aria-labelledby="nav-request-tab">
   <%= render "users/buddy_requests" %>
  </div>
</div>



<!-- USERS END -->

app/views/users/show.html.erb
<div class="min-height-container">
  <div class="row background">
    <!--PROFILE COLONNE -->
    <div class="col-xs-12 col-sm-4">
      <div class="col profile">
        <div class="edit-button"  >
          <% if current_user== @user%>
          <%= link_to 'Edit', edit_user_registration_path(@user) %>
          <% end %>
        </div>

        <% if !@user.photo.blank? %>
          <div class="avatar-profile">
            <img src= "<%= @user.photo %>", class="rounded-circle" style="height: 140px; width: 140px;" alt="">
          </div>
        <% else %>
          <div class="avatar-profile">
            <%= gravatar_for_show @user %>
          </div>
        <% end %>

        <div class="profile-header">
          <h3><strong class="name"> <%= @user.first_name.capitalize %>  <%= @user.last_name.capitalize %></strong></h3>
          <%= link_to  new_message_path(to: @user), class: "message-icon" do %>
                <i class="far fa-envelope fa-lg"></i>
          <% end %>
          <p class="profile-info">
            <%= image_tag "localisation-golf.png", alt: "alttext", style: "width: 14px; margin-right: 6px" %>
            <%= @user.current_city %>
            <br>
            <%= image_tag "icon-golf.png", alt: "alttext", style: "width: 16px; margin-right: 6px" %>
            Handicap: <%= @user.handicap %>
            <br>
          <% if @user.language %>
          <%= image_tag "speaker.png", alt: "alttext", style: "width: 20px; margin-right: 6px" %><%= @user.language %>
          <% end %>
          </p>
        </div>
        <div class="about-me">
          <p>
            About me:
            <br>
            <%= @user.about_me %>
          </p>
        </div>
      </div>
    </div>

    <!-- GAMES COLONNE -->
    <div class="col-xs-12 col-sm-8 color-test4">
      <div class="row games">
          <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Upcoming Games</a>
            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Past Games</a>
          </div>
      </div>

      <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">

          <div>
            <h3 class="next-game-h3">Next Game</h3>
          </div>
          <!-- NEXT GAME CARD -->
          <% unless @next_game.nil? %>
          <div class="row">
            <div class="card-product">
              <img class="course-img" src="<%= @next_game.course.attachments[0].photo.url %>" />
              <div class="card-product-infos">
                <h3 class="game-name"><%= @next_game.name %></h3>
                  <p>
                    <%= image_tag "localisation-golf.png", alt: "alttext", style: "width: 15px; margin-right: 6px"%>
                    <%= @next_game.course.name %>
                    <br>
                    <span class="space-btw-info"><%= image_tag "calendar.png", alt: "alttext", style: "width: 14px; margin-right: 6px" %> <%= @next_game.time.strftime("%d/%m/%Y") %>

                    </span>
                    <span> <%= image_tag "clock.png", alt: "alttext", style: "width: 15px; margin-right: 6px"%><%= @next_game.time.strftime("%I:%M %p") %></span>
                  </p>

                  <%= link_to game_path(@next_game) do%>
                  <div class="btn btn-success view-button">
                    <p>View Game</p>
                  </div>
                  <% end %>

                  <% unless @next_game.user == current_user || current_user.in_game?(@next_game) %>
                  <%= link_to game_guests_path(@next_game), method: :post do %>
                  <div class="btn btn-info join-button">
                    <p>Join game</p>
                  </div>
                  <% end %>
                  <% end %>

              </div>
            </div>
          </div>
          <% else %>
            <p>Your are not registered on a game yet...</p>
          <% end %>
          <div>
            <h3 class="future-games">Future Games</h3>
          </div>
          <!-- FUTURE GAMES CARD -->
          <% @future_games.each do |game| %>
          <div class="row space-btw-card">
            <div class="card-product">
              <img class="course-img" src="<%= game.course.attachments[0].photo.url %>" />
              <div class="card-product-infos">
                <h3 class="game-name"><%= game.name %></h3>
                <p><%= image_tag "localisation-golf.png", alt: "alttext", style: "width: 15px; margin-right: 6px"%><%= game.course.name %>
                  <br>
                  <span class="space-btw-info"><%= image_tag "calendar.png", alt: "alttext", style: "width: 14px; margin-right: 6px" %> <%= game.time.strftime("%d/%m/%Y") %>
                    </span>
                    <span> <%= image_tag "clock.png", alt: "alttext", style: "width: 15px; margin-right: 6px"%><%= game.time.strftime("%I:%M %p") %></span>
                  <%= link_to game_path(game) do%>
                  <div class="btn btn-success view-button">
                    <p>View Game</p>
                  </div>
                  <% end %>

                  <% unless @next_game.user == current_user || current_user.in_game?(@next_game) %>
                  <%= link_to game_guests_path(@next_game), method: :post do %>
                  <div class="btn btn-info join-button">
                    <p>Join game</p>
                  </div>
                  <% end %>
                  <% end %>

                </p>
              </div>
            </div>
          </div>
          <% end %>
        </div>
        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
          <!-- PAST GAMES CARD -->
          <% @past_games.each do |game| %>
          <div class="row space-btw-card">
            <div class="card-product">
              <img class="course-img" src="<%= game.course.attachments[0].photo.url %>" />
              <div class="card-product-infos">
                <h3 class="game-name"><%= game.name %></h3>
                <p><%= image_tag "localisation-golf.png", alt: "alttext", style: "width: 15px; margin-right: 6px"%><%= game.course.name %>
                  <br>
                  <span class="space-btw-info"><%= image_tag "calendar.png", alt: "alttext", style: "width: 14px; margin-right: 6px" %> <%= game.time.strftime("%d/%m/%Y") %>
                    </span>
                    <span> <%= image_tag "clock.png", alt: "alttext", style: "width: 15px; margin-right: 6px"%><%= game.time.strftime("%I:%M %p") %></span>
                  <%= link_to game_path(game) do%>
                  <div class="btn btn-success view-button">
                    <p>View Game</p>
                  </div>
                  <% end %>


                </p>
              </div>
            </div>
          </div>
          <% end %>



        </div>
      </div>
    </div>
  </div>
</div>