config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/games/upcoming', to: 'games#upcoming', as: :games_upcoming
  get '/games/past', to: 'games#past', as: :games_past
  get '/games/public', to: 'games#public_games', as: :games_public
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  resources :users, only: [:index, :show] do
    resources :wishlists
  end
  # Routes for HasFriendship
    post '/users/:id/friendships',    to: 'friendships#request_frd', as: :friendships_request
    post '/users/:id',   to: 'friendships#confirm_frd', as: :friendships_confirm
    post '/users/:id',   to: 'friendships#decline_frd', as: :friendships_decline
    delete '/users/:id',  to: 'friendships#remove_frd', as: :friendships_remove
  resources :list_preferences
  resources :courses do
    resources :attachments
  end
  resources :games do
    resources :attachments
    resources :guests, only: [:index, :create, :update]
    resources :likes
    resources :wishgames
  end

  resources :guests, only: [:destroy]
  get '/games/approve_user/:id', to: 'guests#approve_user', as: :approve_user
  get '/games_buddies', to: 'games#games_buddies', as: :games_buddies
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
      collection do
      delete :empty_trash
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# raise %>
<div class="footer <%= params[:controller] == 'users/registrations' ? 'hidden' : ''  %> <%= params[:controller] == 'devise/sessions' ? 'hidden' : ''  %>" >
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright color-copyright">
    © Copyright 2019 GOLFY Buddy. All rights reserved
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="menu-left row">
    <div class="menu-left-home">
      <% if params[:controller] == 'pages' %>
        <li class="menu-left1">
      <% else %>
        <li class="menu-left2">
      <% end %>
      <%= link_to "Home", root_path %>
    </div>
    <div class="menu-left-games">
      <% if params[:controller] == 'games' || params[:controller] == 'courses' %>
        <li class="menu-left1">
      <% else %>
        <li class="menu-left2">
      <% end %>
      <%= link_to "Games", games_path %>
    </div>
    <div class="menu-left-buddies">

      <% if params[:controller] == 'users' %>
        <li class="menu-left1">
      <% else %>
        <li class="menu-left2">
      <% end %>
      <%= link_to "Buddies", users_path %>
    </div>
  </div>
  <!-- BURGER DROPDOWN -->
  <div class="burgerleft"  onclick="myFunction(this)">
    <div class="bar1"></div>
    <div class="bar2"></div>
    <div class="bar3"></div>

    <div id="burgerDrop" class="drop-menu-left" >
      <div class="drop-menu-text">
      <%= link_to "Home", root_path %>
      </div>
      <div class="drop-menu-text">
      <%= link_to "Games", games_path %>
      </div>
      <div class="drop-menu-text">
      <%= link_to "Buddies", users_path %>
      </div>
    </div>

    <script>
      function myFunction(x) {
        x.classList.toggle("change");
        document.getElementById("burgerDrop").classList.toggle("show");
      }
      window.onclick = function(event) {
        if (!event.target.matches('.burgerleft')) {
          var dropdowns = document.getElementsByClassName("drop-menu-left");
          var i;
          for (i = 0; i < dropdowns.length; i++) {
            var openDropdown = dropdowns[i];
              if (openDropdown.classList.contains('show')) {
                openDropdown.classList.remove('show');
              }
          }
          var dropdowns = document.getElementsByClassName("burgerleft");
          var i;
          for (i = 0; i < dropdowns.length; i++) {
            var openDropdown = dropdowns[i];
              if (openDropdown.classList.contains('change')) {
                openDropdown.classList.remove('change');
              }
          }
        }
      }
    </script>
  </div>

  <!-- LOGO -->
  <div class="logo">
    <%= link_to root_path do %>
      <%= image_tag "Logo_GolfyBuddy_v2.png", style: "width: 85px;"%>
    <% end %>
  </div>

  <div class="row menu-right">
    <% if user_signed_in? %>
      <!-- HOST BUTTON -->
      <div class="button-host">
          <%= link_to "Host a game", new_game_path, class: "host-button" %>
      </div>

    <div class="avatar1">
        <!-- AVATAR -->
        <% if current_user.photo.blank? %>
          <%= image_tag gravatar_image_url(current_user.email), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <!-- NOTIFICATION SUR AVATAR -->
        <% if @unread_conversations_count > 0 %>
          <span class="badge">
            <%= @unread_conversations_count %>
          </span>
        <% end %>
    <% else %>
    <!-- LOGIN BUTTON -->
      <div class="login-button">
        <%= link_to "Login", new_user_session_path %>
      </div>
    <% end %>
    </div>
  </div>
    <!-- DROPDOWN MENU -->
    <% if user_signed_in? %>
      <div id="dropRight" class="drop-menu-right">
        <div class="drop-menu-text">
        <%= link_to 'Messages', conversations_path %>
        </div>

        <div class="drop-menu-text">
        <%= link_to 'My profile', user_path(current_user) %>
        </div>

        <div class="drop-menu-text">
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
        </div>

      </div>
    <% end %>
</div>