config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/games/upcoming', to: 'games#upcoming', as: :games_upcoming
  get '/games/past', to: 'games#past', as: :games_past
  get '/games/public', to: 'games#public_games', as: :games_public
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  resources :users, only: [:index, :show] do
    resources :wishlists
  end
  # Routes for HasFriendship
    post '/users/:id/friendships',    to: 'friendships#request_frd', as: :friendships_request
    post '/users/:id',   to: 'friendships#confirm_frd', as: :friendships_confirm
    post '/users/:id',   to: 'friendships#decline_frd', as: :friendships_decline
    delete '/users/:id',  to: 'friendships#remove_frd', as: :friendships_remove
  resources :list_preferences
  resources :courses do
    resources :attachments
  end
  resources :games do
    resources :attachments
    resources :guests, only: [:index, :create, :update]
    resources :likes
    resources :wishgames
  end

  resources :guests, only: [:destroy]
  get '/games/approve_user/:id', to: 'guests#approve_user', as: :approve_user
  get '/games_buddies', to: 'games#games_buddies', as: :games_buddies
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
      collection do
      delete :empty_trash
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :course
  belongs_to :user
  has_many :guests, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :wishgames, dependent: :destroy
  has_many :wishlists, through: :wishgames
  accepts_nested_attributes_for :attachments
  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name, :options, :date],
    associated_against: {
      course: [ :name, :address ]
    },
    using: {
      tsearch: { prefix: true }
    }
  validates :number_players, presence: true

  filterrific :default_filter_params => { :sorted_by => 'created_at_desc' },
            :available_filters => %w[
            sorted_by
            search_query
            search_location
            with_course_id
            with_date
          ]

  scope :search_query, ->(query) {
    return nil  if query.blank?
    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      ('%'+e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conditions = 2
    where(
      terms.map {
        or_clauses = [
          "LOWER(games.name) LIKE ?",
          "LOWER(games.about_game) LIKE ?",
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }

    scope :search_location, ->(query) {
    return nil if query.blank?
    # condition query, parse into individual keywords
    terms = query.downcase.split(/,/)
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      ('%'+e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conditions = 2
    where(
      terms.map {
        or_clauses = [
          "LOWER(games.location) ILIKE ?",
          "LOWER(games.country) ILIKE ?",
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' OR '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }

  scope :sorted_by, ->(sort_option) {
    # extract the sort direction from the param value.
    direction = (sort_option =~ /asc$/) ? 'asc' : 'desc'
    games = Game.arel_table
    case sort_option.to_s
    when /^created_at_/
      # order("games.created_at #{direction}")
      order(games[:created_at].send(direction))
    when /^name_/
      # order("LOWER(games.name) #{direction}")
      order(games[:name].lower.send(direction))
    when /^number_players_/
      order(games[:number_players].send(direction))
    when /^time_/
      order(games[:time].send(direction))
    else
      raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }

  scope :with_course_id, ->(course_ids) {
    where(:course_id => [*course_ids])
  }

  scope :with_date, -> (date){
    where("time >= ? AND time < ?", date.to_date, date.to_date + 1)
  }

  # delegate :name, :to => :course, :prefix => true

  scope :upcoming, -> { where("time>= ?", [Date.today]).order('date ASC, created_at ASC') }
  scope :past, -> { where("time < ?", [Date.today]).order('date DESC, created_at DESC') }
  scope :public_games, -> { where(privacy: 'public') }
  scope :play_more, -> { where(user: current_user) }

  self.per_page = 12

  def users
    users = guests.map do |guest|
      User.find(guest.user_id).first_name
    end
    return users
  end

  def self.options_for_sorted_by
    [
      ['Name (a-z)', 'name_asc'],
      ['Name (z-a)', 'name_desc'],
      ['Date (newest first)', 'time_desc'],
      ['Date (oldest first)', 'time_asc'],
      ['Number of players (2-4)', 'number_players_asc'],
      ['Number of players (4-2)', 'number_players_desc'],
    ]
  end

  def self.options_for_select
    games = Game.arel_table
    order(games[:course_id]).distinct.pluck(:course_id)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :upcoming, :past, :public_games]
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :set_admin_gb

  # GET /games
  def index
    # @games = Game.upcoming
      # @upcoming_games = Game.where("date >= ?", [Date.today]).order('time ASC, created_at ASC')
      # @past_games = Game.where("date < ?", [Date.today]).order('time DESC, created_at DESC')

      # if user_signed_in?
      #   @wishlist = Wishlist.where(user_id: current_user.id)
      #   @wishgames = Wishgame.where(wishlist_id: @wishlist.ids[0])
      #   @games_wish = []
      #   @wishgames.each do |wish|
      #     @games_wish << wish.game
      #   end
      # end

    # if params[:game_query].present?
    #   query_date = Date.parse(params[:game_query][:date])
    #   # query_location = params[:game_query][:location]
    #   @games_by_date = Game.where("time > ? AND time < ?", query_date, query_date + 1)
    #   # @games = @games_by_date.select { |game| ("#{game.course.address} ILIKE %#{query_location}%") }

    # # elsif params[:query].present?
    # #   @games = Game.joins(:user, :course).global_search(params[:query])
    # #   @upcoming_games = @upcoming_games.global_search(params[:query])
    # #   @past_games = @past_games.global_search(params[:query])
    # else
      (@filterrific = initialize_filterrific(
        Game,
        params[:filterrific],
        select_options: {
          sorted_by: Game.options_for_sorted_by,
          with_course_id: Course.options_for_select_course,
          with_date: Game.options_for_select,
        },
        )) || return
          @games = @filterrific.find.page(params[:page]).where('time >= ?', [Date.today])
      respond_to do |format|
        format.html
        format.js
      end
      # @guests = Guest.where(game: [@games])
    # end
  end

  def upcoming
    @games = Game.upcoming.map do |game|
      unless game.number_guests.nil?
      game.guests.size < game.number_guests
      end
    end
    # @games = @games.paginate(page: params[:page])
    render :index
  end


  def with_address
    @games = Game.with_address
    render :index
  end

  def past
    @games = Game.past
    render :index
  end

  def public_games
    @games = Game.public_games
    render :index
  end

  def play_more
    @games = Game.play_more
    render :index
  end

  # GET /games/1
  def show
    @attachments = @game.attachments.all
    @guest = @game.guests.find_by(user: current_user)
    @user = User.find(@game.user.id)
    @marker = [{
      lat: @game.course.latitude,
      lng: @game.course.longitude,
      image_url: helpers.asset_url('marker-gb.png')
    }]
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  def create
    @game = Game.new(game_params)
    @game.user = current_user
    @game.location = @game.course.address
    @game.country = @game.course.country
      if @game.save
        redirect_to @game, notice: 'Game was successfully created.'
        @admin.send_message(@game.user.friends, "Your buddy #{@game.user.first_name} just created a new game!", "Would you join #{@game.user.first_name}")
      else
        render :new
      end
  end

  # PATCH/PUT /games/1
  def update
      if @game.update(game_params)
      @game.location = @game.course.address
      @game.country = @game.course.country
      @game.save
        redirect_to @game, notice: 'Game was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
      redirect_to games_url, notice: 'Game was successfully destroyed.'
  end

  def games_buddies
    upcoming_games = Game.where("date >= ?", [Date.today]).order('date ASC, created_at ASC')
    @upcoming_games_buddies = []
    upcoming_games.each do |upgame|
      if upgame.user.friends_with?(current_user)
        @upcoming_games_buddies << upgame
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :options, :number_players, :number_guests, :privacy, :date, :time, :game_price, :booked, :tournament, :about_game, :course_id, :user_id, :location, :country)
    end
end

app/views/games/_list.html.erb
<!-- DEBUT DES GAME CARDS -->
  <div id="filterrific_results_games">
  <div class="game-cards-container min-height-container">
    <% if !@filterrific.with_date.nil? && @filterrific.with_date.to_date < Date.today %>
    <p style='text-align: center'>Please, choose a date in the future, not in the past (you know playing with Bobby Jones is impossible, right?)</p>
    <% elsif @games.blank? %>
    <p style='text-align: center'>Sorry, no game matches your search</p>
    <% end %>
    <% @games.each do |game| %>
    <% if game.privacy != "private" || (game.privacy == "private" && game.user.friends_with?(current_user)) %>
    <%= link_to game_path(game), class: "game-card-link" do %>
    <div class="game-card">
      <img src="<%= game.course.attachments[0].photo.url %>" />
      <div class="game-card-infos">

        <div class="game-name-game-course">
          <h3><%= game.name %></h3>
          <h4><%= game.course.name %></h4>
        </div>


        <div class="date-time-buddies">
          <div class="date-time">
            <p><%= game.time.strftime("%d/%m/%Y") %></p>
            <p><%= game.time.strftime("%H:%M") %></p>
            <p><b><%= game.likes.count %> <%= (game.likes.count) < 2 ? 'Like' : 'Likes'%></b></p>
          </div>
          <!-- GAME BUDDIES -->
          <div class="buddies">
            <!-- GAME HOST -->
            <% if !game.user.photo.blank? %>
            <img src="<%= game.user.photo %>" class="game-card-user avatar-bordered" id="game-host" />
            <% else %>
            <%= image_tag gravatar_image_url(game.user.email), class: "game-card-user avatar-bordered", id: "game-host" %>
            <% end %>

            <!-- LOOP DES GUESTS ET DU NOMBRE DE PLAYERS -->
            <% (game.number_players - 1).times do |i| %>
            <% if game.guests[i].nil? %>
            <%= image_tag asset_path("available_spot.png"), class: "game-card-user avatar-bordered", id: "guest-#{(i + 1)}" %>
            <% elsif !game.guests[i].user.photo.blank? %>
            <%= cl_image_tag game.guests[i].user.photo, class: "game-card-user avatar-bordered", id: "guest-#{(i + 1)}" %>
            <% else %>
            <%= image_tag gravatar_image_url(game.guests[i].user.email), class: "game-card-user avatar-bordered", id: "guest-#{(i + 1)}" %>
            <% end %>
            <% end %>
          </div>
        </div>

      </div>
    </div>
    <% end %>
    <% end %>
    <% end %>
  </div>
</div>
  <!-- FIN DES GAME CARDS -->

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/games_buddies.html.erb
        <h1>My buddies games</h1>
              <ul>
            <% @upcoming_games_buddies.each do |game| %>
                <li>
                  <%= game.user.first_name %> <%= game.user.last_name %>
                  <%= game.name %>
                  <%= game.date %>
                </li>
                <% end %>
              </ul>

app/views/games/index.js.erb
<% js = escape_javascript(
  render(
    :partial => 'games/list',
    :locals => { :games => @games }
  )
) %>
$("#filterrific_results_games").html("<%= js %>");

app/views/games/new.html.erb
<!-- NEW GAME -->

<%= render 'form', game: @game %>
<!--
<%= link_to 'Back', games_path %> -->

app/views/games/show.html.erb
<div style="background-image: url('<%= @game.course.attachments[0].photo.url %>'); background-size:cover; background-position: center; height: 60vh" class="w-100 image-container">
  <div class="holes text-center">
    <%= @game.options %>
  </div>
</div>

<div class="container">
  <div class="container">



      <div class="row ">


      <!-- GAME INFO STARTS HERE -->
      <div class="game-info col-lg-8 col-sm-12">
        <div>
          <h1 class="text-warning text-left pt-4 source-sans-pro" >

            <%= @game.name %>
          </h1>
        </div>
        <div class="container">

      <div class="row">

    <div class="pl-1">
      <% if @game.booked %>
        <svg width="25" height="27" viewBox="0 0 25 27" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M20.9375 10.125L24.3125 1.6875H4.0625C4.0625 0.675 3.3875 0 2.375 0C1.3625 0 0.6875 0.675 0.6875 1.6875V25.3125C0.6875 26.325 1.3625 27 2.375 27C3.3875 27 4.0625 26.325 4.0625 25.3125V18.5625H24.3125L20.9375 10.125Z" fill="#70B56F"/>
        </svg>

        <span>Booked</span>
        <% else %>
        <svg width="25" height="27" viewBox="0 0 25 27" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M20.9375 10.125L24.3125 1.6875H4.0625C4.0625 0.675 3.3875 0 2.375 0C1.3625 0 0.6875 0.675 0.6875 1.6875V25.3125C0.6875 26.325 1.3625 27 2.375 27C3.3875 27 4.0625 26.325 4.0625 25.3125V18.5625H24.3125L20.9375 10.125Z" fill="#E86C60"/>
        </svg>


        <span>To be booked</span>
      <% end %>
    </div>

      <div class="pl-5">
        <svg width="24" height="27" viewBox="0 0 24 27" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M21.1966 4.12695H2.35517C1.73073 4.12768 1.13205 4.41779 0.690503 4.93361C0.248957 5.44943 0.000623505 6.14882 0 6.8783V23.845C0.000623505 24.5744 0.248957 25.2738 0.690503 25.7897C1.13205 26.3055 1.73073 26.5956 2.35517 26.5963H21.1966C21.821 26.5956 22.4197 26.3055 22.8612 25.7897C23.3028 25.2738 23.5511 24.5744 23.5517 23.845V6.8783C23.5511 6.14882 23.3028 5.44943 22.8612 4.93361C22.4197 4.41779 21.821 4.12768 21.1966 4.12695ZM21.1966 25.6792H2.35517C1.93875 25.6792 1.53939 25.4859 1.24493 25.142C0.950481 24.798 0.785058 24.3314 0.785058 23.845V10.0882H22.7667V23.845C22.7667 24.3314 22.6013 24.798 22.3068 25.142C22.0124 25.4859 21.613 25.6792 21.1966 25.6792Z" fill="#676767" fill-opacity="0.8"/>
        <path d="M18.449 3.2099V0.917114C18.449 0.67388 18.3663 0.440609 18.2191 0.268617C18.0719 0.0966243 17.8722 0 17.664 0C17.4558 0 17.2561 0.0966243 17.1088 0.268617C16.9616 0.440609 16.8789 0.67388 16.8789 0.917114V3.2099H18.449Z" fill="#676767" fill-opacity="0.8"/>
        <path d="M6.67314 3.2099V0.917114C6.67314 0.67388 6.59043 0.440609 6.4432 0.268617C6.29598 0.0966243 6.09629 0 5.88808 0C5.67987 0 5.48019 0.0966243 5.33297 0.268617C5.18574 0.440609 5.10303 0.67388 5.10303 0.917114V3.2099H6.67314Z" fill="#676767" fill-opacity="0.8"/>
        </svg>

        <%= @game.time.strftime( "%d/%m/%Y") %>
      </div>

      <div class="pl-5">
        <svg width="27" height="27" viewBox="0 0 27 27" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M13.4932 0C6.0345 0 0 6.04125 0 13.5C0 20.9587 6.0345 27 13.4932 27C20.952 27 27 20.9587 27 13.5C27 6.04125 20.952 0 13.4932 0ZM13.5 24.3C7.533 24.3 2.7 19.467 2.7 13.5C2.7 7.533 7.533 2.7 13.5 2.7C19.467 2.7 24.3 7.533 24.3 13.5C24.3 19.467 19.467 24.3 13.5 24.3ZM14.175 6.75H12.15V14.85L19.2308 19.1025L20.25 17.442L14.175 13.8375V6.75Z" fill="#676767" fill-opacity="0.8"/>
        </svg>

        <%= @game.time.strftime( "%H" + ":" + "%M" ) %>
      </div>
        <div class="pl-5">
            <svg width="13" height="24" viewBox="0 0 13 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M6.99803 10.5333C4.09921 9.74667 3.16699 8.93333 3.16699 7.66667C3.16699 6.21333 4.45678 5.2 6.61493 5.2C8.88801 5.2 9.73084 6.33333 9.80746 8H12.6297C12.5403 5.70667 11.1994 3.6 8.53045 2.92V0H4.69941V2.88C2.222 3.44 0.229862 5.12 0.229862 7.69333C0.229862 10.7733 2.66896 12.3067 6.23183 13.2C9.42436 14 10.0629 15.1733 10.0629 16.4133C10.0629 17.3333 9.43713 18.8 6.61493 18.8C3.98428 18.8 2.9499 17.5733 2.78389 16H2.19214e-07C0.153242 18.92 2.24754 20.56 4.69941 21.1067V24H8.53045V21.1333C11.0206 20.6667 13 19.1333 13 16.4C13 12.6133 9.89686 11.3333 6.99803 10.5333Z" fill="#676767" fill-opacity="0.9"/>
            </svg>
            <%= @game.game_price %>
          </div>
      </div>
      <div class="class4 ">
        <div class="pt-2">
          <svg width="24" height="32" viewBox="0 0 24 32" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M23 12.0475C23 19.5 12 30.5 12 30.5C12 30.5 1 19.5 1 12.0475C1 5.0565 6.6845 1 12 1C17.3155 1 23 5.0565 23 12.0475Z" stroke="#676767" stroke-opacity="0.8" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="square"/>
        <path d="M12 16C14.2091 16 16 14.2091 16 12C16 9.79086 14.2091 8 12 8C9.79086 8 8 9.79086 8 12C8 14.2091 9.79086 16 12 16Z" stroke="#676767" stroke-opacity="0.8" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="square"/>
        </svg>

          <%= link_to @game.course.name, @game.course %>
        </div>


        <div class="about_game">
          <%= @game.about_game %>
        </div>
      </div>
        <div class="row">
          <% if user_signed_in? %>
          <% pre_like = @game.likes.find { |like| like.user_id == current_user.id} %>
            <% if pre_like %>
                <%= link_to  game_likes_path(@game), method: :post, remote: true do %>
                <div id="heart">
                  <i class="fas fa-heart" style= "color: rgba(122, 107, 189, 0.7);"></i>
                </div>
                <% end %>
              <% else %>

                  <%= link_to  game_likes_path(@game), method: :post, remote: true do %>
                  <div id="heart">
                    <i class="far fa-heart" style= "color: rgba(122, 107, 189, 0.7);"></i>
                  </div>
                  <% end %>
            <% end %>
          <% end %>

          <div class="pl-2" id="like-txt"><%= @game.likes.count %> <%= @game.likes.count < 2 ? 'Like' : 'Likes'%></div>
        </div>
      </div>
      <div class="row bottom justify-content-between">

        <div class="col-md-3 col-sm-12">
          <strong>Players</strong>
           <p class="text-secondary"> <%= @game.number_players%> players maximum</p>
        </div>

        <div class="guests text-secondary col-md-4 col-sm-12">


            <div id="buddy-small-pic">
              <% @game.guests.each do |guest|%>
                <% if !guest.user.photo.present? %>
                      <%= image_tag gravatar_image_url(guest.user.email), class: "game-card-user avatar-bordered", id: "guest-1" %>
                      <%# raise %>
                <% else %>
                    <img src="<%= guest.user.photo %>" class="buddy-photo small" alt="">
                <% end %>
              <% end %>
            </div>


          <div id="buddy-small-pic">

          </div>
          <div id="js-guests">
            <p><%= @game.guests.size %> buddies out of <%= @game.number_players - 1 %> have joined the game</p>
          </div>
        </div>


      </div>
    </div>
<!-- GAME INFO ENDS HERE -->
<!-- BUDDY CARD STARTS HERE -->
  <div class="col-lg-4 col-sm-12 text-center">


      <div class="buddy-card text-center" id="buddy-card-show">
        <h2 class="pt-3">Host</h2>
        <%= link_to user_path(@game.user_id) do%>
          <% if @game.user.photo %>
            <div>
              <img src= "<%= @game.user.photo%>", class="buddy-photo" id="okok" alt="">
            </div>
          <% else %>
            <div class="buddy-photo">
            <%= gravatar_for_show(@game.user) %>
            </div>
          <% end %>
          <div class="text-center text-warning pt-3">
            <strong><%= @user.first_name %> <%= @user.last_name %></strong>
          </div>
          <% end %>

          <div class="pt-3 text-secondary">
            <svg width="22" class="mr-2" height="29" viewBox="0 0 22 29" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M21 11.0432C21 17.8182 11 27.8182 11 27.8182C11 27.8182 1 17.8182 1 11.0432C1 4.68773 6.16773 1 11 1C15.8323 1 21 4.68773 21 11.0432Z" stroke="#676767" stroke-opacity="0.8" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="square"/>
              <path d="M11.0004 14.636C13.0087 14.636 14.6367 13.008 14.6367 10.9996C14.6367 8.99134 13.0087 7.36328 11.0004 7.36328C8.99207 7.36328 7.36401 8.99134 7.36401 10.9996C7.36401 13.008 8.99207 14.636 11.0004 14.636Z" stroke="#676767" stroke-opacity="0.8" stroke-width="1.5" stroke-miterlimit="10" stroke-linecap="square"/>
            </svg>
            <% if !@user.current_city || @user.current_city == "" %>
            NA
            <% elsif @user.current_city %>
            <%= @user.current_city %>
            <% end %>
          </div>

          <div class="pt-2 text-secondary">
            <svg width="25" class="mr-2" height="23" viewBox="0 0 25 23" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M6.36667 13.975C3.14207 14.79 1 16.2282 1 17.8666C1 20.4073 6.14893 22.4666 12.5 22.4666C18.8511 22.4666 24 20.4073 24 17.8666C24 15.3259 18.8511 13.2666 12.5 13.2666" stroke="#676767" stroke-opacity="0.9" stroke-miterlimit="10" stroke-linecap="square"/>
              <path d="M9.43335 17.8667V1L16.3333 4.06667L9.43335 7.13333" stroke="#676767" stroke-opacity="0.9" stroke-miterlimit="10"/>
            </svg>

            <% if @user.handicap %>
            Handicap: <%= @user.handicap %>
            <% else %>
            Handicap : NA
            <% end %>

            <div class="pt-2">
              <% if @user.language %>
              <% if @user.language == "English" %>
              <% url =  "https://www.countryflags.io/gb/flat/24.png" %>
              <% elsif @user.language == "French" %>
              <% url =  "https://www.countryflags.io/fr/flat/24.png" %>
              <% elsif @user.language == "Spanish" %>
              <% url =  "https://www.countryflags.io/es/flat/24.png" %>
              <% else %>
              <% url =  "https://www.countryflags.io/#{@user.language[0..1].downcase}/flat/24.png" %>
              <% end %>
              <% end %>
              <img class= "mr-1" src= <%= url %>>
              <%= @user.language %>
            </div>

            <div class="text-center message">
              <% unless current_user == @user %>

                <div class="pt-2">
                <div class="pt-1">
              <%= link_to  '<i class="fas fa-envelope fa-lg"></i>  Send message'.html_safe, new_message_path(to: @user), class: "send-button-small"%>
            </div>
          </div>



              <% end %>
            </div>
        </div>
      </div>
  </div>
        <!-- BUDDY CARD ENDS HERE -->
  </div>


  <div class="container">


  </div>


      <div class="container">


    <% if current_user != @game.user %>
            <div class="text-center pt-4">
                  <% if user_signed_in? %>
                    <% if  @game.number_players > @game.guests.count && !current_user.in_game?(@game) %>
                      <%= link_to game_guests_path(@game), remote: true, method: :post  do %>
                        <button id='joinButton' class="btn btn-success btn-join col-6">Join Game</button>
                      <% end %>
                    <% else %>
                      <%= link_to game_guests_path(@game), remote: true, method: :post  do %>
                        <button id='joinButton' class="btn btn-info btn-join col-6">Leave Game</button>
                      <% end %>
                    <% end %>
                  <% end %>
            </div>

              <!-- <div class="text-center">
                <% if user_signed_in? %>
                  <% pre_wish = @game.wishgames.find { |wishgame| wishgame.wishlist.user_id == current_user.id} %>
                    <% if pre_wish%>
                      <%= button_to 'Remove from wishlist', game_wishgame_path(@game, pre_wish), method: :delete %>
                    <% else %>
                      <%= button_to 'Add to wishlist', game_wishgames_path(@game), method: :post, class: "btn btn-warning btn-join col-6" %>
                    <% end %>
                  <% end %>
              </div> -->

      <% end %>

    <% @attachments.each do |att| %>
      <%= image_tag att.photo_url %>
      <%= link_to "Edit Attachment", edit_game_attachment_path(att) %>
    <% end %>

    <% if current_user == @game.user   %>
      <% @game.guests.where(status: "pending").each do |guest| %>
      <p>
        <%= User.find(guest.user_id).first_name %>
        <%= link_to 'Approve', approve_user_path(guest.user_id) %> |

      </p>
      <% end %>
      <div class="text-center pt-3">
        <%= link_to 'Back', games_path, class: "btn btn-warning" %>
        <%= link_to 'Edit', edit_game_path(@game), class: "btn btn-warning" %>
        <%= link_to 'Delete', game_path(@game), method: :delete, class: "btn btn-danger" %>
      </div>

    <% end %>
    </div>

    </div>
  </div>
  </div>

  <div
      id="map"
      style="width: 100%; height: 500px; margin-top: 32px;"
      data-markers="<%= @marker.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>
</div>